
// src/app/terms-conditions/page.tsx
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { FileText, Users, Shield, AlertTriangle, Info, Scale } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - Foss AI',
  description: 'Read the Terms and Conditions for using the Foss AI application. Understand your rights and responsibilities as a user.',
  openGraph: {
    title: 'Foss AI Terms of Service',
    description: 'Official terms governing the use of Foss AI, including user conduct, intellectual property, and limitations of liability.',
    images: [
      {
        url: '/terms-og-image.png',
        width: 1200,
        height: 630,
        alt: 'Foss AI Terms and Conditions',
      },
    ],
  },
};

export default function TermsConditionsPage() {
  return (
    <div className="container mx-auto min-h-[calc(100vh-8rem)] py-12 sm:py-16 px-4 sm:px-6 lg:px-8">
      <Card className="w-full max-w-3xl mx-auto shadow-2xl border-primary/20 rounded-xl overflow-hidden">
        <CardHeader className="text-center p-8 sm:p-10 bg-gradient-to-br from-primary/10 via-transparent to-primary/5 rounded-t-xl">
          <div className="inline-flex items-center justify-center p-4 sm:p-5 bg-gradient-to-br from-accent to-accent/80 rounded-full mb-5 sm:mb-8 mx-auto ring-2 ring-accent/40 shadow-lg text-accent-foreground">
            <FileText className="h-12 w-12 sm:h-16 sm:w-16" />
          </div>
          <CardTitle className="text-4xl sm:text-5xl font-extrabold text-primary tracking-tight">
            Terms and Conditions
          </CardTitle>
          <CardDescription className="text-lg sm:text-xl text-muted-foreground mt-3 sm:mt-4 max-w-2xl mx-auto">
            Please read these terms carefully. Last Updated: {new Date().toLocaleDateString()}.
          </CardDescription>
        </CardHeader>
        <CardContent className="p-6 sm:p-8 md:p-10 text-base text-foreground/90 leading-relaxed prose prose-lg dark:prose-invert max-w-none marker:text-accent">
          <p>
            Welcome to Foss AI ("Application", "Service"). These Terms and Conditions ("Terms") govern your use of our application. By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
          </p>

          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><Info className="h-6 w-6 mr-3 text-accent"/>1. Acceptance of Terms (Placeholder)</h2>
          <p>
            By creating an account or using Foss AI, you confirm that you have read, understood, and agree to be bound by these Terms. If you are using the Service on behalf of an organization, you are agreeing to these Terms for that organization and promising that you have the authority to bind that organization to these terms.
          </p>

          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><Users className="h-6 w-6 mr-3 text-accent"/>2. User Accounts (Placeholder)</h2>
          <p>
            When you create an account with us, you must provide information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
          </p>

          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><Shield className="h-6 w-6 mr-3 text-accent"/>3. Use of Service (Placeholder)</h2>
          <p>
            You agree not to use the Service for any unlawful purpose or in any way that interrupts, damages, or impairs the service. You agree not to misuse the AI capabilities, such as generating harmful, unethical, or illegal content. Foss AI reserves the right to suspend or terminate your access for misuse.
          </p>
          <p>
            The content generated by Foss AI, including research reports and images, is for informational and assistive purposes. While we strive for accuracy and usefulness, we do not guarantee the veracity, completeness, or suitability of AI-generated content for any specific purpose. You are responsible for critically evaluating and verifying any information obtained through the Service before relying on it.
          </p>
          
          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><Scale className="h-6 w-6 mr-3 text-accent"/>4. Intellectual Property (Placeholder)</h2>
          <p>
            The Service and its original content (excluding content provided by users or generated by AI for users), features, and functionality are and will remain the exclusive property of Foss AI and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Foss AI.
          </p>
           <p>
            You retain ownership of the intellectual property rights in the content you input into the Service. By using the Service, you grant Foss AI a non-exclusive, worldwide, royalty-free license to use, process, and transmit your input content solely for the purpose of providing and improving the Service. AI-generated output specific to your queries is for your use, subject to the limitations and disclaimers herein.
          </p>


          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><AlertTriangle className="h-6 w-6 mr-3 text-accent"/>5. Disclaimer of Warranties & Limitation of Liability (Placeholder)</h2>
          <p>
            The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Foss AI makes no warranties, expressed or implied, regarding the operation of the service or the information, content, or materials included therein.
          </p>
          <p>
             In no event shall Foss AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>

          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><Info className="h-6 w-6 mr-3 text-accent"/>6. Changes to Terms (Placeholder)</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
          </p>

          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><Users className="h-6 w-6 mr-3 text-accent"/>7. Governing Law (Placeholder)</h2>
          <p>
            These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction, e.g., State of Texas, United States], without regard to its conflict of law provisions.
          </p>
          
          <h2 className="text-2xl font-semibold text-primary flex items-center mt-8 mb-4"><FileText className="h-6 w-6 mr-3 text-accent"/>8. Contact Us (Placeholder)</h2>
          <p>
            If you have any questions about these Terms, please contact us at legal@fossai.example.com (Placeholder).
          </p>
           <p className="mt-6 text-sm text-muted-foreground">
            This is a placeholder terms and conditions document. In a real application, this would be a comprehensive legal document drafted by a legal professional.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
