
// src/app/api-docs/page.tsx
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Code2, Construction, InfoIcon, ShieldCheck } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'API Documentation - ScholarAI',
  description: 'Explore the ScholarAI API for programmatic access to research tools and generative AI capabilities.',
  openGraph: {
    title: 'API Documentation - ScholarAI',
    description: 'Integrate ScholarAI\'s powerful research and AI functionalities into your applications.',
  },
};

export default function ApiDocsPage() {
  return (
    <div className="container mx-auto min-h-[calc(100vh-8rem)] py-10 px-4 sm:px-6 lg:px-8">
      <Card className="w-full max-w-3xl mx-auto shadow-xl border-primary/20">
        <CardHeader className="text-center p-6 sm:p-8 bg-gradient-to-br from-primary/10 via-transparent to-primary/5 rounded-t-xl">
          <div className="inline-flex items-center justify-center p-3 sm:p-4 bg-gradient-to-br from-accent to-accent/80 rounded-full mb-4 sm:mb-6 mx-auto ring-2 ring-accent/40 shadow-lg text-accent-foreground">
            <Code2 className="h-10 w-10 sm:h-12 sm:w-12" />
          </div>
          <CardTitle className="text-3xl sm:text-4xl font-extrabold text-primary tracking-tight">ScholarAI API Documentation</CardTitle>
          <CardDescription className="text-lg sm:text-xl text-muted-foreground mt-2 sm:mt-3">
            Integrate ScholarAI's power into your own applications and workflows.
          </CardDescription>
        </CardHeader>
        <CardContent className="p-6 sm:p-8 space-y-8 text-base sm:text-lg text-foreground/90 leading-relaxed prose prose-base sm:prose-lg dark:prose-invert max-w-none marker:text-accent">
          <p>
            Welcome to the ScholarAI API documentation. Our API is designed to provide developers with programmatic
            access to the core functionalities of ScholarAI, including AI-driven query formulation, advanced
            research synthesis, and comprehensive report generation.
          </p>
          
          <Alert variant="default" className="bg-primary/5 border-primary/20 text-primary dark:bg-primary/10 dark:border-primary/30 dark:text-primary-foreground/90">
            <Construction className="h-6 w-6 text-primary" />
            <AlertTitle className="font-semibold text-lg text-primary">API Under Active Development</AlertTitle>
            <AlertDescription className="text-primary/80 dark:text-primary-foreground/80 mt-1">
              The ScholarAI API is currently under active development and is not yet publicly available.
              This page serves as a placeholder and an overview of our planned API capabilities.
              We are working diligently to bring these features to you soon. Stay tuned for updates!
            </AlertDescription>
          </Alert>
              
          <section>
            <h2 className="text-2xl sm:text-3xl font-semibold text-primary flex items-center mt-8 mb-4">
               <InfoIcon className="h-6 w-6 sm:h-7 sm:w-7 mr-3 text-accent" />
               Planned API Features
            </h2>
            <p>We aim to provide a RESTful API with clear endpoints for key ScholarAI services. Our initial focus will be on enabling developers to:</p>
            <ul className="list-disc list-outside space-y-2 pl-5 sm:pl-6 mt-3">
              <li><strong>Formulate Research Queries:</strong> Submit a complex research question or topic and receive a set of optimized search queries generated by our AI.</li>
              <li><strong>Synthesize Information:</strong> Provide a list of queries or raw text data (e.g., abstracts) to obtain a coherent, AI-generated summary of key insights.</li>
              <li><strong>Generate Research Reports:</strong> Programmatically initiate the creation of detailed, structured research reports based on a research question and optional contextual summary.</li>
              <li><strong>Generate Conceptual Images:</strong> Request AI-generated images for specific topics or concepts to visually enhance research outputs.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl sm:text-3xl font-semibold text-primary flex items-center mt-8 mb-4">
               <ShieldCheck className="h-6 w-6 sm:h-7 sm:w-7 mr-3 text-accent" />
               Authentication & Access
            </h2>
            <p>
              Secure access to the API will be managed through API keys. Details on obtaining API keys, authentication mechanisms (e.g., Bearer tokens), rate limits, and usage policies will be provided upon the API's official launch.
            </p>
          </section>
          
          <p className="text-center pt-6 text-muted-foreground text-sm sm:text-base">
            We are excited about the future possibilities the ScholarAI API will unlock for developers and researchers alike!
            Thank you for your interest.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
